markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: false
rdiscount:
  extensions: [smart]
name: Hacker Within, Illinois
description: An initial blog and site for THW at UI at Urbana-Chamkpaign
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin

